config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo_list, optional: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	has_many :tasks, inverse_of: :todo_list, dependent: :destroy
	accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }
	# accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
    # 3.times do
    @todo_list.tasks.build
    # end
  end

  # GET /todo_lists/1/edit
  def edit
    # 3.times do
      @todo_list.tasks.build
    # end
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    puts todo_list_params
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:name, :tasks_attributes => [:id, :_destroy, :todo_list_id, :name, :completed, :due])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_row(name, f,association, **args )
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize, f: builder)
		end
		link_to(name,'#', class: "add_fields " +args[:class], data: {id: id, fields: fields.gsub("\n","")})
		
	end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :todo_list_name %>
  </div>
  <!-- <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Task Name</th>
        <th>Completed</th>
        <th>Due</th>
      </tr>
    </thead>
    <tbody class="fields">
      <%= form.fields_for :tasks do |builder|%>
        <%= render 'task', f: builder %>
      <% end %>
    </tbody>
  </table> -->

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Task Name</th>
        <th>Completed</th>
        <th>Due</th>
      </tr>
    </thead>
    <tbody class="tasks">
      <%= form.fields_for :tasks do |builder|%>
        <%= render 'task_fields', f: builder %>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
    <%#= link_to_add_row("Add Task", form, :tasks, class: 'btn btn-primary')%>

    <!-- from cocoon gem -->
    <%= link_to_add_association("Add Task", form, :tasks, class: "btn btn-primary", data: {
      association_insertion_node: '.tasks', association_insertion_method: :append
    })%>
  </div>
<% end %>

app/views/todo_lists/_task.html.erb
<tr>
	<td>
		<%= f.hidden_field :_destroy %>
		<%= link_to 'Delete', '#', class: 'remove_record' %>
	</td>
	<td><%= f.text_field :name , label: false %></td>
	<td><%= f.check_box :completed , label: false %></td>
	<td><%= f.text_field :due , label: false, as: :string %></td>
</tr>

app/views/todo_lists/_task_fields.html.erb
<tr class="nested-fields">
	<td>
		<%= link_to_remove_association("Remove Tasks", f) %>
	</td>
	<td><%= f.text_field :name , label: false %></td>
	<td><%= f.check_box :completed , label: false %></td>
	<td><%= f.text_field :due , label: false, as: :string %></td>
</tr>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.name %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_list.name %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>